import {useRef,useState} from 'react';
import {type Project} from './model';
import {type SaveTarget} from './workspace';
import {aiContext,applyProposal,proposalDiff,stateHash,type Proposal} from './aiOperations';
import {defaultMedia} from './media';
import {Field} from './Controls';
type Result={proposal?:Proposal;image?:string;documentId:string;baseHash:string;sectionId:string;scope:'section'|'page';model:string;providerId:string;quality?:string};
async function api(query='',body?:unknown){const response=await fetch('/api/playground/ai'+query,{credentials:'same-origin',...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});const value=await response.json();if(!response.ok)throw Error(value.error||'AI is unavailable. Keep editing manually.');return value;}
export function AIAssist({project:p,target,documentId,selected,guard,edit}:{project:Project;target:SaveTarget|null;documentId:string;selected:string;guard:()=>()=>boolean;edit:(p:Project)=>void}){
 const [request,setRequest]=useState(''),[scope,setScope]=useState<'section'|'page'>('section'),[available,setAvailable]=useState(false),[images,setImages]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('Optional AI is disabled until configured and approved.'),[result,setResult]=useState<Result|null>(null);
 const [pending,setPending]=useState('');
 const lock=useRef(false),requestGuard=useRef<(()=>boolean)|null>(null),cancelled=useRef(false);
 if(import.meta.env.VITE_PLAYGROUND_AI_UI!=='true')return null;
 async function check(){try{const status=await api();if(target&&status.ownerId!==target.owner)throw Error('Account changed. Refresh account projects.');setAvailable(status.enabled);setImages(status.enabled&&status.images);setMessage(status.enabled?'AI is available for an explicit request.':'AI is disabled. Manual editing and free exports are available.');}catch(e){setAvailable(false);setMessage((e as Error).message);}}
 function receive(value:{state:string;result:Result|null}){if(value.result){setResult(value.result);setMessage('Review the proposed changes. Apply changes only this local design.');}else setMessage(value.state==='unknown'?'Provider outcome is unknown. The reservation stays pending; do not repeat this request.':value.state==='reserved'?'Still pending. Check this result again later.':'No valid proposal was returned. Your design is unchanged.');}
 async function generate(kind:'text'|'image'){
  if(lock.current||!target||!available||!request.trim())return;lock.current=true;setBusy(true);setResult(null);cancelled.current=false;const valid=guard();requestGuard.current=valid;
  try{const baseHash=await stateHash(p);if(!valid())throw Error('Workspace changed. Review your request again.');const key=crypto.randomUUID();setPending(key);const value=await api('',{kind,request,scope,context:aiContext(p,selected,scope),requestId:key,projectId:target.id,revisionId:target.head,expectedOwner:target.owner,documentId,baseHash});if(!valid()){setMessage('AI response ignored because the workspace changed. Make a new request for this design.');return;}if(!cancelled.current)receive(value);}catch(e){setMessage((e as Error).message+' Check this request before creating another; a timeout may already have incurred cost.');}finally{lock.current=false;setBusy(false);}
 }
 async function apply(){if(!result||!target)return;const valid=guard();try{const status=await api();if(status.ownerId!==target.owner)throw Error('Account changed. Refresh account projects.');if(!valid()||result.documentId!==documentId||!requestGuard.current?.()||await stateHash(p)!==result.baseHash)throw Error('This proposal is stale. Your design changed; make a new request from the current design.');if(!valid())throw Error('Workspace changed.');if(result.proposal)edit(applyProposal(p,result.sectionId,result.scope,result.proposal));else if(result.image){if(result.sectionId===p.sections[0].id&&p.brand?.locks.includes('logo'))throw Error('The brand logo is locked.');const sourceId=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(result.image))),b=>b.toString(16).padStart(2,'0')).join('');if(!valid())throw Error('Workspace changed.');edit({...p,sections:p.sections.map(s=>s.id===result.sectionId?{...s,image:result.image!,media:{...defaultMedia(),sourceId,sourceName:'Generated draft',generation:{model:result.model,quality:result.quality||'low',providerId:result.providerId}}}:s)});}setResult(null);setMessage('Applied as one undoable local edit. Account Save remains manual.');}catch(e){setMessage((e as Error).message);}}
 let diff:ReturnType<typeof proposalDiff>=[];try{if(result?.proposal)diff=proposalDiff(p,result.sectionId,result.scope,result.proposal);}catch{/* Apply explains stale or locked fields without mutating. */}
 return <details className="pg-project-tools"><summary>Optional AI assistance</summary><button onClick={()=>void check()}>Check AI availability</button><p role="status">{message}</p>{!target&&<p>Open or save an account project first.</p>}<Field label="Describe a change" value={request} maxLength={600} multiline onChange={setRequest}/><div className="pg-field"><label htmlFor="pg-ai-scope">AI change scope</label><select id="pg-ai-scope" value={scope} onChange={e=>setScope(e.target.value as 'section'|'page')}><option value="section">Selected section only</option><option value="page">Page palette and selected section</option></select></div><p>Only this request and relevant text/settings go to the provider. Uploaded images are not sent. Review every proposal before applying.</p><button disabled={!available||!target||busy||request.trim().length<3} onClick={()=>void generate('text')}>Preview AI change</button>{images&&<><p>Generate one low-quality draft from your words. Keep real logos and text as separate uploaded assets. Each new draft is a separate paid request.</p><button disabled={!target||busy||request.trim().length<3} onClick={()=>void generate('image')}>Generate one image draft</button></>}{busy&&<button onClick={()=>{cancelled.current=true;setMessage('Stopped waiting. This does not cancel provider billing. Check the existing result later.');}}>Stop waiting</button>}{pending&&<button disabled={busy} onClick={async()=>{try{receive(await api('?requestId='+encodeURIComponent(pending)));}catch(e){setMessage((e as Error).message);}}}>Check existing result</button>}{result&&<><ul>{diff.map(d=><li key={d.field}><strong>{d.field}</strong>: {d.before} → {d.after}</li>)}</ul>{result.image&&<img className="pg-media-thumb" src={result.image} alt="Generated image proposal"/>}<button onClick={()=>void apply()}>Apply proposal</button><button onClick={()=>setResult(null)}>Discard proposal</button></>}</details>;
}
