import {useState} from 'react';
import {type Project,type Section,type SectionStyle,type Card,type SectionType,sectionKind,labels,newBlock,upgradeProject} from './model';
import {Field,Destination,Range,Color,Toggle} from './Controls';
import {imageData} from './storage';
import {defaultMedia} from './media';
export function StructureControls({project:p,selected,edit,guard,notify}:{project:Project;selected:string;edit:(p:Project)=>void;guard:()=>()=>boolean;notify:(s:string)=>void}) {
 const [type,setType]=useState<SectionType>('about');
 const s=p.sections.find(s=>s.id===selected)||p.sections[0],kind=sectionKind(s);
 const patch=(value:Partial<Section>)=>edit({...p,sections:p.sections.map(v=>v.id===s.id?{...v,...value}:v)});
 const style=s.style||{spacing:p.tokens.spacing,align:'left' as const,background:''};
 const setStyle=(v:Partial<SectionStyle>)=>patch({style:{...style,...v}});
 const cards=s.cards||[];
 const card=(id:string,v:Partial<Card>)=>patch({cards:cards.map(c=>c.id===id?{...c,...v}:c)});
 if(p.schemaVersion===1)return <details className="pg-project-tools"><summary>More page controls</summary><p>Enable repeatable blocks, independent cards and section settings. This is one undoable upgrade; the current renderer stays selected.</p><button onClick={()=>edit(upgradeProject(p))}>Enable flexible sections</button></details>;
 return <details className="pg-project-tools" open><summary>Page structure</summary><div className="pg-field"><label htmlFor="pg-block-type">New block</label><select id="pg-block-type" value={type} onChange={e=>setType(e.target.value as SectionType)}>{(['about','contact','faq','gallery','testimonials','pricing'] as SectionType[]).map(t=><option key={t} value={t}>{labels[t]}</option>)}</select></div><button disabled={p.sections.length>=16} onClick={()=>edit({...p,sections:[...p.sections.slice(0,-1),newBlock(type),p.sections.at(-1)!]})}>Add block</button><small>{p.sections.length} of 16 sections. Select a section above to edit it.</small>
 <h3>{labels[kind]} settings</h3><small>Instance: {s.id}</small>
 {!['header','footer','hero'].includes(kind)&&<button onClick={()=>edit({...p,sections:p.sections.filter(v=>v.id!==s.id)})}>Remove selected block</button>}
 {kind!=='header'&&kind!=='footer'&&<><Range label="This section spacing" min={0} max={160} value={style.spacing} onChange={spacing=>setStyle({spacing})}/><div className="pg-field"><label htmlFor="pg-align">This section alignment</label><select id="pg-align" value={style.align} onChange={e=>setStyle({align:e.target.value as SectionStyle['align']})}>{['left','center','right'].map(v=><option key={v}>{v}</option>)}</select></div><Toggle label="Custom section background" checked={!!style.background} onChange={v=>setStyle({background:v?p.tokens.background:''})}/>{style.background&&<Color label="Section background color" value={style.background} onChange={background=>setStyle({background})}/>}<Toggle label="Override mobile spacing" checked={style.mobileSpacing!==undefined} onChange={v=>setStyle({mobileSpacing:v?style.spacing:undefined})}/>{style.mobileSpacing!==undefined&&<Range label="Mobile section spacing" min={0} max={160} value={style.mobileSpacing} onChange={mobileSpacing=>setStyle({mobileSpacing})}/>}<div className="pg-field"><label htmlFor="pg-mobile-align">Mobile alignment</label><select id="pg-mobile-align" value={style.mobileAlign||''} onChange={e=>setStyle({mobileAlign:(e.target.value||undefined) as SectionStyle['mobileAlign']})}><option value="">Inherit desktop</option>{['left','center','right'].map(v=><option key={v}>{v}</option>)}</select></div></>}
 {kind==='header'&&<><p>Each label has its own destination. The legacy two-link menu remains until you customize it.</p><button onClick={()=>patch({navigation:[...(s.navigation||[]),{label:'New link',href:'#'}].slice(0,6)})} disabled={(s.navigation?.length||0)>=6}>Add navigation link</button>{s.navigation?.map((n,i)=><fieldset key={i}><legend>Link {i+1}</legend><Field label="Navigation label" value={n.label} maxLength={60} onChange={label=>patch({navigation:s.navigation!.map((v,j)=>i===j?{...v,label}:v)})}/><Destination value={n.href} onChange={href=>patch({navigation:s.navigation!.map((v,j)=>i===j?{...v,href}:v)})}/><button onClick={()=>patch({navigation:s.navigation!.filter((_,j)=>j!==i)})}>Remove link {i+1}</button></fieldset>)}</>}
 {['gallery','faq','testimonials','pricing'].includes(kind)&&<><p>{kind==='testimonials'?'Add only testimonials you have permission to publish.':kind==='pricing'?'Add your real services and prices. These cards do not create checkout.':'Add your own content. Each card has an independent image.'}</p>{cards.map((c,i)=><fieldset key={c.id}><legend>Card {i+1}</legend><Field label="Card heading" value={c.title} maxLength={240} onChange={title=>card(c.id,{title})}/><Field label="Card text" multiline value={c.description} onChange={description=>card(c.id,{description})}/>{c.image&&<img className="pg-media-thumb" src={c.image} alt="Card thumbnail"/>}<label className="pg-upload">Replace card image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const valid=guard();try{const image=await imageData(f);const sourceId=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(image))),b=>b.toString(16).padStart(2,'0')).join('');if(!valid()){notify('Workspace changed. Choose the card image again.');return;}card(c.id,{image,media:{...defaultMedia(),sourceId,sourceName:f.name.slice(0,120)}});}catch(e){notify((e as Error).message);}}}/></label><Field label="Card image description" value={c.alt} maxLength={300} onChange={alt=>card(c.id,{alt})}/><button onClick={()=>card(c.id,{image:''})}>Remove card image</button><button disabled={i===0} onClick={()=>{const next=[...cards];[next[i-1],next[i]]=[next[i],next[i-1]];patch({cards:next});}}>Move card up</button><button disabled={i===cards.length-1} onClick={()=>{const next=[...cards];[next[i+1],next[i]]=[next[i],next[i+1]];patch({cards:next});}}>Move card down</button><button onClick={()=>patch({cards:cards.filter(v=>v.id!==c.id)})}>Remove card {i+1}</button></fieldset>)}<button disabled={cards.length>=12} onClick={()=>patch({cards:[...cards,{id:'card-'+crypto.randomUUID(),title:'',description:'',image:'',alt:''}]})}>Add card</button></>}
 {kind==='contact'&&<p>This is a contact design with a link. No form submission service is connected.</p>}
 </details>;
}
