import {useState} from 'react';
import {sourceAnswer} from '../../functions/_shared/platform/knowledge';
const problems=[
 {label:'Customers cannot find the right product',title:'Make the first choice clear.',body:'A branded entrance groups polos and layers into direct shopping paths. Category labels should match the choices customers actually make.',image:'/images/services/liberty-desktop-20260921.png',alt:'Actual Liberty storefront category entrance',href:'https://stores.inksoft.com/liberty_christian_early_learnin/shop/home',link:'Open the delivered storefront'},
 {label:'Customers need sizing guidance',title:'Put guidance beside the decision.',body:'The Liberty storefront links its size guide from the entrance, before customers commit to a product. This is a visible interface feature; conversion improvement has not been measured.',image:'/images/services/liberty-mobile-20260921.png',alt:'Actual mobile Liberty storefront with product paths and size guide',href:'https://stores.inksoft.com/liberty_christian_early_learnin/shop/home',link:'Inspect the public store'},
 {label:'Only approved employees should enter',title:'Check eligibility without publishing the roster.',body:'The PERNR case study explains a private roster check and retry path. Its public demonstration uses fictional identifiers; it never connects to a real employee roster.',image:'/images/case-studies/pernr-access-gate.png',alt:'Public PERNR case-study demonstration; fictional identifiers',href:'/work/pernr-access-gate',link:'Read the access-gate case study'},
];
export function ProblemExplorer(){const [selected,setSelected]=useState(0),p=problems[selected];return <section className="ew-shell service-task"><p className="ew-eyebrow">Start with the friction</p><h2>What is getting in the customer’s way?</h2><div className="service-task__choices">{problems.map((item,i)=><button key={item.label} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{item.label}</button>)}</div><div className="service-task__result" aria-live="polite"><div><h3>{p.title}</h3><p>{p.body}</p><a href={p.href}>{p.link} →</a></div><img src={p.image} alt={p.alt} width="1200" height="800" loading="lazy"/></div></section>}
const questions=['What can help a print shop organize promo photos?','What does Wellway help with?','How does the PERNR access gate work?'];
export function SupportedAnswerDemo(){const [question,setQuestion]=useState(questions[0]);const answer=sourceAnswer(question);return <section className="ew-shell service-task"><p className="ew-eyebrow">Try a supported task</p><h2>Inspect the answer and its sources.</h2><p>This demonstration uses the published project catalogue. No AI request is made.</p><label>Choose a question<select value={question} onChange={e=>setQuestion(e.target.value)}>{questions.map(q=><option key={q}>{q}</option>)}</select></label><article aria-live="polite"><h3>Published-source answer</h3><p>{answer.answer}</p><ul>{answer.sources.map(s=><li key={s.href}><a href={s.href}>{s.title}</a></li>)}</ul><small>Fictional health records in Wellway are demonstration data. Private employee records and customer photos are never part of this example.</small></article></section>}
