import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { deflateRawSync } from 'node:zlib';
// A deterministic ZIP with no third-party packaging service and no runtime generation.
const names = [
  'index.html',
  'styles.css',
  'script.js',
  'README.md',
  'LICENSE.txt',
];
const crcTable = Array.from({ length: 256 }, (_, n) => {
  for (let k = 0; k < 8; k++) n = n & 1 ? 0xedb88320 ^ (n >>> 1) : n >>> 1;
  return n >>> 0;
});
const crc32 = (bytes) => {
  let crc = 0xffffffff;
  for (const n of bytes) crc = crcTable[(crc ^ n) & 255] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
};
const local = [],
  central = [];
let offset = 0;
for (const name of names) {
  // Text sources must yield the same purchased bytes on Windows and Linux.
  const file = Buffer.from((await readFile('products/cinematic-starter/' + name, 'utf8')).replace(/\r\n/g, '\n'));
  const data = deflateRawSync(file);
  const filename = Buffer.from('eidos-cinematic-starter/' + name);
  const crc = crc32(file);
  const header = Buffer.alloc(30);
  header.writeUInt32LE(0x04034b50);
  header.writeUInt16LE(20, 4);
  header.writeUInt16LE(8, 8);
  header.writeUInt16LE(0x5d21, 12);
  header.writeUInt32LE(crc, 14);
  header.writeUInt32LE(data.length, 18);
  header.writeUInt32LE(file.length, 22);
  header.writeUInt16LE(filename.length, 26);
  local.push(header, filename, data);
  const directory = Buffer.alloc(46);
  directory.writeUInt32LE(0x02014b50);
  directory.writeUInt16LE(20, 4);
  directory.writeUInt16LE(20, 6);
  directory.writeUInt16LE(8, 10);
  directory.writeUInt16LE(0x5d21, 14);
  directory.writeUInt32LE(crc, 16);
  directory.writeUInt32LE(data.length, 20);
  directory.writeUInt32LE(file.length, 24);
  directory.writeUInt16LE(filename.length, 28);
  directory.writeUInt32LE(offset, 42);
  central.push(directory, filename);
  offset += header.length + filename.length + data.length;
}
const directory = Buffer.concat(central),
  end = Buffer.alloc(22);
end.writeUInt32LE(0x06054b50);
end.writeUInt16LE(names.length, 8);
end.writeUInt16LE(names.length, 10);
end.writeUInt32LE(directory.length, 12);
end.writeUInt32LE(offset, 16);
const archive = Buffer.concat([...local, directory, end]);
await writeFile(
  'functions/_shared/platform/kitArchive.ts',
  '// Generated by scripts/build-kit.mjs. Served only after payment verification.\nexport const kitArchiveBase64 = ' +
    JSON.stringify(archive.toString('base64')) +
    ';\n',
);
await mkdir('public/kit-preview', { recursive: true });
for (const name of names.slice(0, 3))
  await copyFile(
    'products/cinematic-starter/' + name,
    'public/kit-preview/' + name,
  );
const preview = await readFile('public/kit-preview/index.html', 'utf8');
await writeFile(
  'public/kit-preview/index.html',
  preview.replace(
    '<head>',
    '<head><meta name="robots" content="noindex, follow">',
  ),
);
console.log(
  'Packaged cinematic starter: ' +
    archive.length +
    ' bytes, ' +
    names.length +
    ' files.',
);
