import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,ctx,signup} from './playground-test-fixture';
import {onRequestPost as save} from '../functions/api/playground/projects';
import {onRequestGet as get,onRequestPost as generate} from '../functions/api/playground/ai';
import {ensureAI,cost,type Usage,type AIConfig} from '../functions/_shared/platform/playgroundAI';
import {createProject,upgradeProject} from '../src/playground/model';
import {aiContext,stateHash,applyProposal,validateProposal} from '../src/playground/aiOperations';
const config:AIConfig={model:'fixture-only',pricing:{version:'mock-1',input:1,cachedInput:0.1,cacheWrite:1.25,output:2,imageInput:1,imageOutput:2,cachedImageInput:0.1},accountMicro:100000,globalMicro:200000,maxInputBytes:12000,maxOutputTokens:1000};
const usage:Usage={input:100,cachedInput:0,cacheWrite:0,output:50,reasoning:10,imageInput:0,imageOutput:0,cachedImageInput:0};
async function setup(){const f=fixture(),alice=await signup(f.env,'alice'),bob=await signup(f.env,'bobby'),p=upgradeProject(createProject());const saved=await (await save(ctx(f.env,'/api/playground/projects',{document:p},alice.headers))).json();const owner=String(f.sql.prepare("SELECT id FROM eidos_email_members WHERE username='alice'").get()!.id);Object.assign(f.env,{EIDOS_RUNTIME:'sentinel',EIDOS_PLAYGROUND_AI_ENABLED:'true',EIDOS_PLAYGROUND_AI_KILL:'false',EIDOS_PLAYGROUND_AI_CONFIG:JSON.stringify(config)});await ensureAI(f.env);f.sql.exec('UPDATE eidos_pg_ai_control SET enabled=1');const input={kind:'text',request:'Shorten the headline',scope:'section',context:aiContext(p,'hero','section'),requestId:crypto.randomUUID(),projectId:saved.id,revisionId:saved.revision,expectedOwner:owner,documentId:'workspace-one',baseHash:await stateHash(p)};return {...f,alice,bob,p,input};}
test('strict operations, page scope, unsafe URLs and brand locks preserve input',()=>{const p=upgradeProject(createProject()),before=JSON.stringify(p);p.brand={businessName:'Name',tone:'Clear',locks:['palette','font','name']};assert.throws(()=>applyProposal(p,'hero','section',{ops:[{field:'tokens.accent',value:'#ff0000'}]}),/scope/);assert.throws(()=>applyProposal(p,'hero','page',{ops:[{field:'tokens.accent',value:'#ff0000'}]}),/locked/);assert.throws(()=>applyProposal(p,'header','section',{ops:[{field:'section.title',value:'Changed'}]}),/locked/);assert.throws(()=>applyProposal(p,'hero','section',{ops:[{field:'section.href',value:'javascript:alert(1)'}]}),/unsafe/);assert.throws(()=>validateProposal({ops:[{field:'glass.edge',value:'1'}]}));assert.throws(()=>validateProposal({ops:[{field:'section.title',value:'A',script:'x'}]}));assert.equal(JSON.stringify({...p,brand:undefined}),before);assert.equal(cost(usage,config.pricing),200);assert.throws(()=>cost({...usage,cachedInput:101},config.pricing));});
test('disabled and missing-config paths make zero provider calls; owner replay and pending requests are isolated',async()=>{const f=await setup();let calls=0,release!:()=>void;const held=new Promise<void>(r=>release=r);f.env.EIDOS_PLAYGROUND_AI_PROVIDER=async()=>{calls++;await held;return {status:'completed',model:config.model,requestId:'mock-response',usage,proposal:{ops:[{field:'section.title',value:'Short heading'}]}};};
 try {f.env.EIDOS_PLAYGROUND_AI_ENABLED='false';assert.equal((await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers))).status,503);f.env.EIDOS_PLAYGROUND_AI_ENABLED='true';const cfg=f.env.EIDOS_PLAYGROUND_AI_CONFIG;delete f.env.EIDOS_PLAYGROUND_AI_CONFIG;assert.equal((await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers))).status,503);f.env.EIDOS_PLAYGROUND_AI_CONFIG=cfg;assert.equal(calls,0);
 const one=generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers));while(calls===0)await new Promise(r=>setTimeout(r,1));const duplicate=await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers));assert.equal((await duplicate.json()).state,'reserved');const two=await generate(ctx(f.env,'/api/playground/ai',{...f.input,requestId:crypto.randomUUID()},f.alice.headers));assert.equal(two.status,429);assert.equal(calls,1);release();const response=await one;assert.equal(response.status,200,await response.clone().text());assert.equal((await response.json()).state,'completed');assert.equal((await (await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers))).json()).state,'completed');assert.equal(calls,1);
 assert.equal((await get(ctx(f.env,'/api/playground/ai?requestId='+f.input.requestId,undefined,f.bob.headers))).status,404);assert.equal((await generate(ctx(f.env,'/api/playground/ai',f.input,f.bob.headers))).status,409);assert.equal((await generate(ctx(f.env,'/api/playground/ai',{...f.input,request:'Different'},f.alice.headers))).status,409);
 }finally{release();f.sql.close();}});
test('ambiguous provider failure retains money and concurrency; quota denial never calls provider',async()=>{const f=await setup();let calls=0;f.env.EIDOS_PLAYGROUND_AI_PROVIDER=async()=>{calls++;throw Error('timeout');};try{f.env.EIDOS_PLAYGROUND_AI_CONFIG=JSON.stringify({...config,accountMicro:1});assert.equal((await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers))).status,429);assert.equal(calls,0);f.env.EIDOS_PLAYGROUND_AI_CONFIG=JSON.stringify(config);assert.equal((await (await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers))).json()).state,'unknown');assert.equal((await (await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers))).json()).state,'unknown');assert.equal(calls,1);const row=f.sql.prepare('SELECT state,reserved_micro,actual_micro FROM eidos_pg_ai_requests').get()!;assert.equal(row.actual_micro,null);assert.ok(Number(row.reserved_micro)>0);}finally{f.sql.close();}});
test('refusal, truncation and invalid operations are charged but never applied; stale cloud and raw images are rejected',async()=>{const f=await setup();try{for(const status of ['refused','incomplete','completed'] as const){f.env.EIDOS_PLAYGROUND_AI_PROVIDER=async()=>({status,model:config.model,requestId:'mock-rejected',usage,proposal:{ops:[{field:'glass.edge',value:'1'}]}});const r=await generate(ctx(f.env,'/api/playground/ai',{...f.input,requestId:crypto.randomUUID()},f.alice.headers));assert.equal((await r.json()).state,'rejected');}assert.equal(f.sql.prepare('SELECT SUM(actual_micro) n FROM eidos_pg_ai_requests').get()!.n,600);const extra={...f.input,context:{...f.input.context,section:{...f.input.context.section,image:'data:image/png;base64,abc'}}};assert.equal((await generate(ctx(f.env,'/api/playground/ai',extra,f.alice.headers))).status,400);await save(ctx(f.env,'/api/playground/projects',{id:f.input.projectId,expectedRevision:f.input.revisionId,document:{...f.p,name:'New head'}},f.alice.headers));assert.equal((await generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers))).status,409);}finally{f.sql.close();}});

test('global monetary reservation is atomic across different accounts',async()=>{const f=await setup();let calls=0,release!:()=>void;const held=new Promise<void>(r=>release=r);f.env.EIDOS_PLAYGROUND_AI_PROVIDER=async()=>{calls++;await held;return {status:'refused',model:config.model,requestId:'mock-global',usage};};try{
 const bobSaved=await (await save(ctx(f.env,'/api/playground/projects',{document:f.p},f.bob.headers))).json();const bobOwner=String(f.sql.prepare("SELECT id FROM eidos_email_members WHERE username='bobby'").get()!.id);
 const cfg={...config,globalMicro:15000,accountMicro:15000};f.env.EIDOS_PLAYGROUND_AI_CONFIG=JSON.stringify(cfg);
 const a=generate(ctx(f.env,'/api/playground/ai',f.input,f.alice.headers));for(let i=0;!calls&&i<100;i++)await new Promise(r=>setTimeout(r,1));if(!calls)throw Error(await (await a).text());const heldMicro=Number(f.sql.prepare('SELECT reserved_micro FROM eidos_pg_ai_requests').get()!.reserved_micro);f.env.EIDOS_PLAYGROUND_AI_CONFIG=JSON.stringify({...config,globalMicro:heldMicro*2-1,accountMicro:heldMicro*2-1});const b=await generate(ctx(f.env,'/api/playground/ai',{...f.input,projectId:bobSaved.id,revisionId:bobSaved.revision,expectedOwner:bobOwner,requestId:crypto.randomUUID()},f.bob.headers));assert.equal(b.status,429);assert.equal(calls,1);release();await a;
 }finally{release();f.sql.close();}});
test('image draft is explicit, uses separate pricing and produces owned embedded bytes without implicit save',async()=>{const f=await setup();let calls=0;f.env.EIDOS_PLAYGROUND_AI_PROVIDER=async input=>{calls++;assert.equal(input.kind,'image');return {status:'completed',model:'fixture-image',requestId:'mock-image',usage:{...usage,input:50,output:0,reasoning:0,imageOutput:100},image:'data:image/png;base64,iVBORw0KGgo='};};try{const input={...f.input,kind:'image'};assert.equal((await generate(ctx(f.env,'/api/playground/ai',input,f.alice.headers))).status,503);assert.equal(calls,0);f.env.EIDOS_PLAYGROUND_IMAGE_ENABLED='true';f.env.EIDOS_PLAYGROUND_AI_CONFIG=JSON.stringify({...config,imageModel:'fixture-image',imageMaxMicro:20000,imagePricing:{...config.pricing,version:'mock-image',input:5,imageOutput:30}});const r=await generate(ctx(f.env,'/api/playground/ai',input,f.alice.headers));const result=await r.json();assert.equal(result.state,'completed');assert.match(result.result.image,/^data:image/);assert.equal(calls,1);assert.equal(f.sql.prepare('SELECT actual_micro FROM eidos_pg_ai_requests').get()!.actual_micro,3250);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM eidos_pg_revisions').get()!.n,1);assert.equal((await get(ctx(f.env,'/api/playground/ai?requestId='+input.requestId,undefined,f.bob.headers))).status,404);}finally{f.sql.close();}});
